import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#CAD7CA]">
        {/* Navbar */}
        <header className="h-16 flex items-center px-6 bg-[#CAD7CA]">
          <Link
            href="/"
            className="text-[#374426] text-xl font-bold"
          >
            Shared Roots
          </Link>
        </header>

        {/* Page Content */}
        <main>{children}</main>
      </body>
    </html>
  );
}
